import Work3 from "../../assets/work-3.svg";
import Work6 from "../../assets/work-6.svg";

const Menu = [
  {
    id: 1,
    image: Work6,
    title: "threeJS Product View",
    category: "React Web",
    desc: "Using 3D shirt model, you can customize the model by choosing any color, upload any image to apply on the product.",
    link: "https://threejs-product-view.vercel.app/",
  },
  {
    id: 2,
    image: Work6,
    title: "E-commerce website",
    category: "React Web",
    desc: "Functionality of the cart system, api work, adding/removing products, and a unique design",
    link: "https://multi-shopping-react.vercel.app/",
  },
  {
    id: 3,
    image: Work3,
    title: "E-commerce app",
    category: "React Native",
    desc: "Functionality of liking, bookmarks, product's more options with sharing and reporting.",
    link: "https://github.com/Hartz-byte/app-design-native",
  },
  {
    id: 4,
    image: Work6,
    title: "Draft.js Editor",
    category: "React Web",
    desc: "Rich text editing, custom styling for bold, heading, red-colored, and underlined text",
    link: "https://demo-editor-nine.vercel.app/",
  },
  {
    id: 5,
    image: Work3,
    title: "Weather Forcast App",
    category: "React Native",
    desc: "Get the current and upcoming days Weather Forcast of any searched city.",
    link: "https://github.com/Hartz-byte/weather-forcast-Native",
  },
  {
    id: 6,
    image: Work6,
    title: "Music player website",
    category: "React Web",
    desc: "Log-in to your spotify account, to play your own library.",
    link: "https://github.com/Hartz-byte/music-player-React",
  },
  {
    id: 7,
    image: Work3,
    title: "E-commerce app",
    category: "React Native",
    desc: "Functionality of liking, adding to favorites, and the cart system logic.",
    link: "https://github.com/Hartz-byte/shop-application-native",
  },
  {
    id: 8,
    image: Work6,
    title: "To-do list",
    category: "React Web",
    desc: "Functionality of adding, removing or updating your to-do list. Stores data locally.",
    link: "https://to-do-list-react-silk.vercel.app/",
  },
  {
    id: 9,
    image: Work3,
    title: "Job finder app",
    category: "React Native",
    desc: "Find jobs through the app, and apply to it.",
    link: "https://github.com/Hartz-byte/job-finder-Native",
  },
  {
    id: 10,
    image: Work6,
    title: "Live Weather website",
    category: "React Web",
    desc: "Check the live weather of any city in the world.",
    link: "https://live-weather-react.vercel.app/",
  },
  {
    id: 11,
    image: Work6,
    title: "Movie Search website",
    category: "React Web",
    desc: "Search any movies/tv shows, related to the searched word.",
    link: "https://github.com/Hartz-byte/movie-search-React",
  },
  {
    id: 12,
    image: Work6,
    title: "Meme generator",
    category: "React Web",
    desc: "Generate memes, quotes, jokes and puzzles.",
    link: "https://github.com/Hartz-byte/meme-generator",
  },
];

export default Menu;
